# Generated by Django 3.0.3 on 2020-02-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('habr', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'contact',
            },
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name_plural': 'notes'},
        ),
    ]
