# Generated by Django 3.0.3 on 2020-02-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20200217_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('about_me', models.CharField(max_length=200)),
                ('telephone_number', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
